// <auto-generated />
using System;
using Groep9_SE7;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Groep9_SE7.Migrations
{
    [DbContext(typeof(OutdoorParadise))]
    [Migration("20200423223409_kids")]
    partial class kids
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Groep9_SE7.Bonus", b =>
                {
                    b.Property<int>("Emp_ID");

                    b.Property<DateTime>("Bonus_date");

                    b.Property<decimal>("Bonus_amount");

                    b.HasKey("Emp_ID", "Bonus_date", "Bonus_amount");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("Groep9_SE7.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Groep9_SE7.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address_1");

                    b.Property<string>("Address_2");

                    b.Property<string>("Big_small")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("City");

                    b.Property<string>("Company_Name");

                    b.Property<int?>("Country");

                    b.Property<decimal?>("Discount");

                    b.Property<string>("First_Name");

                    b.Property<string>("Last_Name");

                    b.Property<int?>("Max_Quantity_Order");

                    b.Property<string>("Phone");

                    b.Property<string>("Region");

                    b.Property<string>("State");

                    b.Property<int?>("Type");

                    b.Property<string>("Zip_Code");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Groep9_SE7.Employees", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bene_day_care")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Bene_health_ins")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Bene_life_ins")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime?>("Birth_Date");

                    b.Property<string>("City");

                    b.Property<int?>("Dept_ID");

                    b.Property<string>("Email");

                    b.Property<string>("Extension");

                    b.Property<string>("Fax");

                    b.Property<string>("First_Name");

                    b.Property<int?>("Job_ID");

                    b.Property<string>("Last_Name");

                    b.Property<int?>("Manager");

                    b.Property<string>("Phone");

                    b.Property<decimal?>("Salary");

                    b.Property<string>("Sex")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Ss_Number");

                    b.Property<DateTime>("Start_Date");

                    b.Property<string>("State");

                    b.Property<string>("Status");

                    b.Property<string>("Street");

                    b.Property<string>("TargetMissed");

                    b.Property<DateTime?>("Termination_Date");

                    b.Property<string>("Zip_Code");

                    b.HasKey("ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Groep9_SE7.Excursion", b =>
                {
                    b.Property<int>("Exc_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("Price");

                    b.HasKey("Exc_ID");

                    b.ToTable("Excursion");
                });

            modelBuilder.Entity("Groep9_SE7.Excursion_planned", b =>
                {
                    b.Property<int>("Excursion");

                    b.Property<int>("Travel_planned");

                    b.HasKey("Excursion", "Travel_planned");

                    b.ToTable("Excursion_planned");
                });

            modelBuilder.Entity("Groep9_SE7.Order_Details", b =>
                {
                    b.Property<int>("Order_detail_code")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Dept_ID");

                    b.Property<int>("Order_number");

                    b.Property<int>("Prod_ID");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("Ship_date");

                    b.Property<decimal?>("Unit_cost");

                    b.Property<decimal?>("Unit_price");

                    b.Property<decimal?>("Unit_sale_price");

                    b.HasKey("Order_detail_code");

                    b.ToTable("Order_Details");
                });

            modelBuilder.Entity("Groep9_SE7.Order_Header", b =>
                {
                    b.Property<int>("Order_number")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cust_ID");

                    b.Property<int?>("Dept_ID");

                    b.Property<int>("Emp_ID");

                    b.Property<DateTime>("Order_date");

                    b.Property<int?>("Order_method");

                    b.Property<string>("Region");

                    b.HasKey("Order_number");

                    b.ToTable("Order_Header");
                });

            modelBuilder.Entity("Groep9_SE7.Training", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Course");

                    b.Property<int?>("Emp_ID");

                    b.Property<int?>("Year");

                    b.HasKey("ID");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("Groep9_SE7.Travel_planned", b =>
                {
                    b.Property<int>("Travel_plan_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Customer");

                    b.Property<DateTime>("Date_end");

                    b.Property<DateTime>("Date_start");

                    b.Property<int>("Travel_product");

                    b.HasKey("Travel_plan_ID");

                    b.ToTable("Travel_planned");
                });

            modelBuilder.Entity("Groep9_SE7.Travel_product", b =>
                {
                    b.Property<int>("Trav_prod_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Kids_Allowed")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("Length");

                    b.Property<int>("Max_capacity");

                    b.Property<int>("Min_capacity");

                    b.Property<int>("Price");

                    b.HasKey("Trav_prod_ID");

                    b.ToTable("Travel_product");
                });
#pragma warning restore 612, 618
        }
    }
}
